---
- name: Verificar instalación de Notepad++
  hosts: all
  gather_facts: false

  tasks:

    - name: Buscar Notepad++
      ansible.windows.win_shell: |
        $apps = Get-ItemProperty `
          "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" ,
          "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" `
          -ErrorAction SilentlyContinue |
          Where-Object { $_.DisplayName -like "Notepad++*" }

        if ($apps) {
            Write-Host "============================================"
            Write-Host "Servidor : $env:COMPUTERNAME"
            Write-Host "Estado   : INSTALADO"
            Write-Host ""

            foreach($app in $apps){
                Write-Host "Nombre   : $($app.DisplayName)"
                Write-Host "Versión  : $($app.DisplayVersion)"
                Write-Host "Editor   : $($app.Publisher)"
                Write-Host "Ruta     : $($app.InstallLocation)"
                Write-Host ""
            }

            Write-Host "============================================"
        }
        else {
            Write-Host "============================================"
            Write-Host "Servidor : $env:COMPUTERNAME"
            Write-Host "Estado   : NO INSTALADO"
            Write-Host "============================================"
        }

      register: resultado

      changed_when: false
      failed_when: false

    - name: Mostrar resultado
      debug:
        var: resultado.stdout
